version: 2
updates:
  - package-ecosystem: "npm"
    directory: "adt/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
